language: generic 
sudo : required
services:
    - docker
before_install:
    - docker build -t ccollot/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true ccollot/docker-react npm run test -- --coverage