language: generic 
sudo : required
services:
    - docker
before_install:
    - docker build -t ccollot/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true ccollot/docker-react npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react-beanapp"
    env: "docker-react-beanapp-env"
    bucket_name: "elasticbeanstalk-eu-west-1-928117197915"
    bucket_path: "docker-react-beanapp"
    on:
        branch: main
    access_key_id : $aws_access_key_id
    secret_access_key : $aws_secret_accesskey